#ifndef _DLL_ADVAPI32_
#define _DLL_ADVAPI32_

#include "DLLLoader.h"

class advapi32 : public DLLLoader {
	DECLARE_CLASS(advapi32)

	DECLARE_FUNCTION7(BOOL, LookupAccountNameW, LPCWSTR, LPCWSTR, PSID, LPDWORD, LPWSTR, LPDWORD, PSID_NAME_USE)
	DECLARE_FUNCTION2(BOOL, ConvertSidToStringSidW, PSID, LPWSTR*)

	DECLARE_FUNCTION4(NTSTATUS, LsaEnumerateAccountRights, LSA_HANDLE, PSID, PLSA_UNICODE_STRING*, PULONG)
	DECLARE_FUNCTION1(NTSTATUS, LsaFreeMemory, PVOID)
	DECLARE_FUNCTION4(NTSTATUS, LsaAddAccountRights, LSA_HANDLE, PSID, PLSA_UNICODE_STRING, ULONG)
	DECLARE_FUNCTION5(NTSTATUS, LsaRemoveAccountRights, LSA_HANDLE, PSID, BOOLEAN, PLSA_UNICODE_STRING, ULONG)
	DECLARE_FUNCTION1(ULONG, LsaNtStatusToWinError, NTSTATUS)
	DECLARE_FUNCTION4(NTSTATUS, LsaOpenPolicy, PLSA_UNICODE_STRING, PLSA_OBJECT_ATTRIBUTES, ACCESS_MASK, PLSA_HANDLE)
};

#endif //_DLL_ADVAPI32_
