#ifndef _DLL_NETAPI32_H_
#define _DLL_NETAPI32_H_

#include "DLLLoader.h"

class netapi32 : public DLLLoader {
	DECLARE_CLASS(netapi32)

	DECLARE_FUNCTION4(DWORD, NetUserGetInfo, LPCWSTR, LPCWSTR, DWORD, LPBYTE*)
	DECLARE_FUNCTION8(DWORD, NetUserGetLocalGroups, LPCWSTR, LPCWSTR, DWORD, DWORD, LPBYTE*, DWORD, LPDWORD, LPDWORD)
	DECLARE_FUNCTION1(DWORD, NetApiBufferFree, LPVOID)
	DECLARE_FUNCTION8(DWORD, NetUserEnum, LPCWSTR, DWORD, DWORD, LPBYTE*, DWORD, LPDWORD, LPDWORD, PDWORD)
	DECLARE_FUNCTION2(DWORD, NetUserDel, LPCWSTR, LPCWSTR)
	DECLARE_FUNCTION4(DWORD, NetUserAdd, LPCWSTR, DWORD, LPBYTE, LPDWORD)
	
	DECLARE_FUNCTION8(DWORD, NetLocalGroupGetMembers, LPCWSTR, LPCWSTR, DWORD, LPBYTE*, DWORD, LPDWORD, LPDWORD, PDWORD_PTR)
	DECLARE_FUNCTION3(DWORD, NetLocalGroupAddMember, LPCWSTR, LPCWSTR, PSID)
	DECLARE_FUNCTION3(DWORD, NetLocalGroupDelMember, LPCWSTR, LPCWSTR, PSID)
	DECLARE_FUNCTION7(DWORD, NetLocalGroupEnum, LPCWSTR, DWORD, LPBYTE*, DWORD, LPDWORD, LPDWORD, PDWORD_PTR)
	DECLARE_FUNCTION4(DWORD, NetLocalGroupAdd, LPCWSTR, DWORD, LPBYTE, LPDWORD)
	DECLARE_FUNCTION2(DWORD, NetLocalGroupDel, LPCWSTR, LPCWSTR)
};

#endif //_DLL_NETAPI32_H_
